version: "3.7"

services:

  nginx:
    image: nginx:latest
    ports:
        - 80:80
        - 443:443
    volumes:
        - ./nginx:/etc/nginx/conf.d
        - ./logs/nginx:/var/log/nginx
        - ./wordpress:/var/www/html
        - ./certs:/etc/letsencrypt
        - ./certs-data:/data/letsencrypt
    links:
        - wordpress
    networks:
      - webnet
    deploy:
      replicas: 1
      update_config:
        parallelism: 2
        delay: 10s
      resources:
        limits:
          cpus: "0.1"
          memory: 50M
      restart_policy:
        condition: on-failure

  mysql:
    image: mariadb:latest
    env_file: .env
    environment: 
      - MYSQL_ROOT_PASSWORD=$MYSQL_ROOT_PASSWORD
      - MYSQL_USER=$MYSQL_USER
      - MYSQL_PASSWORD=$MYSQL_PASSWORD
      - MYSQL_DATABASE=$MYSQL_DATABASE
    ports: 
      - 3306:3306
    volumes: 
      - ./db-data:/var/lib/mysql
    networks:
      - webnet
    deploy: 
      resources:
        limits:
          cpus: "0.1"
          memory: 50M
      replicas: 1
      update_config:
        parallelism: 2
        delay: 10s
      restart_policy: 
        condition: on-failure

  wordpress:
    image: wordpress:latest
    ports:
        - 9000:9000
    volumes:
        - ./wordpress:/var/www/html
    env_file: .env
    environment:
        - WORDPRESS_DB_NAME=$WORDPRESS_DB_NAME
        - WORDPRESS_TABLE_PREFIX=$WORDPRESS_TABLE_PREFIX
        - WORDPRESS_DB_HOST=$WORDPRESS_DB_HOST
        - WORDPRESS_DB_USER=$WORDPRESS_DB_USER
        - WORDPRESS_DB_PASSWORD=$WORDPRESS_DB_PASSWORD
    links:
        - mysql
    networks:
      - webnet
    deploy:
      replicas: 1
      update_config:
        parallelism: 2
        delay: 10s
      resources:
        limits:
          cpus: "0.1"
          memory: 50M
      restart_policy:
        condition: on-failure
    
networks:
  webnet:
