version: "3.7"

services:

  mysql:
    image: mysql:5.7
    environment:
      MYSQL_USER: wordpress
      MYSQL_PASSWORD: aqwe123
      MYSQL_DATABASE: wpdb
    ports: 
      - 3306:3306
    volumes: 
      - $PWD/db-data:/var/lib/mysql
    networks:
      - webnet
    command: '--default-authentication-plugin=mysql_native_password'
    deploy: 
      resources:
        limits:
          cpus: "0.1"
          memory: 50M
      replicas: 1
      placement:
        constraints: [node.id == pmv59qgezia7sgh62de1m10i7]
      update_config:
        parallelism: 2
        delay: 10s

  wordpress:
    image: wordpress:php7.3-fpm-alpine
    ports:
        - 9000:9000
    volumes:
        - $PWD/wordpress:/var/www/html
    environment:
      WORDPRESS_DB_HOST: db
      WORDPRESS_DB_NAME: wp_db
      WORDPRESS_DB_USER: wordpress
      WORDPRESS_DB_PASSWORD: qwe123
    links:
        - mysql
    networks:
      - webnet
    deploy:
      replicas: 1
      placement:
        constraints: [node.id == pmv59qgezia7sgh62de1m10i7]
      update_config:
        parallelism: 2
        delay: 60s
      resources:
        limits:
          cpus: "0.1"
          memory: 50M

  nginx:
    image: nginx:latest
    ports:
        - 80:80
        - 443:443
    volumes:
        - $PWD/nginx:/etc/nginx/conf.d
        - $PWD/logs/nginx:/var/log/nginx
        - $PWD/wordpress:/var/www/html
        - $PWD/certs:/etc/letsencrypt
        - $PWD/certs-data:/data/letsencrypt
    links:
        - wordpress
    networks:
      - webnet
    deploy:
      replicas: 1
      placement:
        constraints: [node.id == pmv59qgezia7sgh62de1m10i7]
      update_config:
        parallelism: 2
        delay: 10s
      resources:
        limits:
          cpus: "0.1"
          memory: 50M
      
networks:
  webnet:
