version: "3.7"

services:

  mysql:
    image: mysql:5.7
    restart: always 
    container_name: mysql
    volumes: 
      - db-data:/var/lib/mysql
    environment:
      MYSQL_DATABASE: exampledb 
      MYSQL_USER: exampleuser
      MYSQL_PASSWORD: examplepass
      MYSQL_RANDOM_ROOT_PASSWORD: '1'
    deploy:
      replicas: 1
      placement:
        constraints: [node.id == pmv59qgezia7sgh62de1m10i7]
      update_config:
        parallelism: 2
        delay: 10s
      resources:
        limits:                                                                                                                                                                                                                                                              
          cpus: "0.1"
          memory: 50M

  wordpress:
    image: wordpress:php7.1-fpm
    restart: always 
    ports:
      - 9000:9000
    volumes:
      - $PWD/wordpress:/var/www/html
    environment:
      WORDPRESS_DB_HOST: mysql
      WORDPRESS_DB_USER: exampleuser
      WORDPRESS_DB_PASSWORD: examplepass
      WORDPRESS_DB_NAME: exampledb
    deploy:
      replicas: 1
      placement:
        constraints: [node.id == pmv59qgezia7sgh62de1m10i7]
      update_config:
        parallelism: 2
        delay: 10s
      resources:
        limits:                                                                                                                                                                                                                                 
          cpus: "0.1"
          memory: 50M

  nginx:
    image: nginx:latest
    ports:
      - 980:80
      - 9443:443
    volumes:
      - $PWD/nginx:/etc/nginx/conf.d
      - $PWD/logs/nginx:/var/log/nginx
      - $PWD/wordpress:/var/www/html
      - $PWD/certs:/etc/letsencrypt
      - $PWD/certs-data:/data/letsencrypt
    links:
      - wordpress
    deploy:
      replicas: 1
      placement:
        constraints: [node.id == pmv59qgezia7sgh62de1m10i7]
      update_config:
        parallelism: 2
        delay: 10s
      resources:
        limits:
          cpus: "0.1"
          memory: 50M
  certbot:
    depends_on:
      - nginx
    image: certbot/certbot
    container_name: certbot
    volumes:
      - $PWD/certbot-etc:/etc/letsencrypt
      - $PWD/wordpress:/var/www/html
    command: certonly --webroot --webroot-path=/var/www/html --email julioapim@gmail.com --agree-tos --no-eff-email --staging -d julio.com -d wp.julio.com 

volumes:
  certbot-etc:
  wordpress:
  db-data:
  nginx:
  certs:
  certs-data:

networks:
  webnet:

